services:
  - type: web
    name: kravex-api
    runtime: node
    rootDir: server
    buildCommand: npm install && npx prisma generate
    preDeployCommand: npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kravex-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: KRAVEX_USE_EMBEDDED_DB
        value: "false"
      - key: KRAVEX_SEED_ON_BOOT
        value: "false"
      - key: PORT
        value: 10000

  - type: web
    name: kravex-web
    runtime: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: kravex-db
    databaseName: kravex
    plan: basic-256mb
