import { Plus } from "lucide-react";
import { useEffect, useState } from "react";
import { Button, DataTable, Field, inputClass, PageTitle } from "../components/UI";
import { api } from "../utils/api";
import { label } from "../utils/format";

const blank = { name: "", niche: "Dentists", prospectsCount: 0, emailsSent: 0, openRate: 0, replyRate: 0, positiveReplies: 0, callsBooked: 0, status: "ACTIVE", notes: "" };
export default function Campaigns() {
  const [campaigns, setCampaigns] = useState([]), [editing, setEditing] = useState(null);
  const [prospects, setProspects] = useState([]);
  const load = () => api.get("/campaigns").then((res) => setCampaigns(res.data));
  useEffect(() => { load(); api.get("/prospects").then((res) => setProspects(res.data)); }, []);
  const save = async (e) => { e.preventDefault(); editing.id ? await api.put(`/campaigns/${editing.id}`, editing) : await api.post("/campaigns", editing); setEditing(null); load(); };
  return <><PageTitle title="Campaign Tracker" subtitle="Monitor outreach volume, open rates, replies, and calls booked." action={<Button onClick={() => setEditing(blank)}><Plus size={16}/> New Campaign</Button>} /><DataTable rows={campaigns} columns={[{ key: "name", label: "Campaign" }, { key: "niche", label: "Niche" }, { key: "emailsSent", label: "Sent" }, { key: "openRate", label: "Open %" }, { key: "replyRate", label: "Reply %" }, { key: "positiveReplies", label: "Positive" }, { key: "callsBooked", label: "Calls" }, { key: "status", label: "Status", render: (r) => label(r.status) }]} />{editing && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/50 p-4"><form onSubmit={save} className="w-full max-w-3xl rounded-lg bg-white p-6 shadow-xl"><h2 className="mb-4 text-xl font-semibold">Campaign</h2><div className="grid gap-4 md:grid-cols-2">{Object.keys(blank).map((key) => key === "notes" ? <Field key={key} label="Notes"><textarea className={inputClass} value={editing[key] || ""} onChange={(e) => setEditing({ ...editing, [key]: e.target.value })} /></Field> : key === "status" ? <Field key={key} label="Status"><select className={inputClass} value={editing.status} onChange={(e) => setEditing({ ...editing, status: e.target.value })}>{["ACTIVE", "PAUSED", "COMPLETED"].map((s) => <option key={s} value={s}>{label(s)}</option>)}</select></Field> : <Field key={key} label={label(key)}><input className={inputClass} type={["prospectsCount", "emailsSent", "openRate", "replyRate", "positiveReplies", "callsBooked"].includes(key) ? "number" : "text"} value={editing[key] ?? ""} onChange={(e) => setEditing({ ...editing, [key]: e.target.value })} /></Field>)}<Field label="Linked prospects"><select multiple className={inputClass} value={editing.prospectIds || editing.prospects?.map((p) => p.prospectId) || []} onChange={(e) => setEditing({ ...editing, prospectIds: Array.from(e.target.selectedOptions).map((option) => option.value) })}>{prospects.map((p) => <option key={p.id} value={p.id}>{p.businessName}</option>)}</select></Field></div><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setEditing(null)}>Cancel</Button><Button>Save</Button></div></form></div>}</>;
}
