import { Download, Plus } from "lucide-react";
import { useEffect, useState } from "react";
import { Button, DataTable, Field, inputClass, PageTitle } from "../components/UI";
import { api } from "../utils/api";
import { dateUk, label } from "../utils/format";

const blank = { clientId: "", leadName: "", businessName: "", email: "", phone: "", source: "COLD_EMAIL", quality: "WARM", status: "NEW", deliveredAt: new Date().toISOString().slice(0, 10), notes: "" };
export default function Leads() {
  const [leads, setLeads] = useState([]), [clients, setClients] = useState([]), [editing, setEditing] = useState(null), [clientId, setClientId] = useState("");
  const load = () => api.get("/leads", { params: { clientId } }).then((res) => setLeads(res.data));
  useEffect(() => { load(); api.get("/clients").then((res) => setClients(res.data)); }, [clientId]);
  const save = async (e) => { e.preventDefault(); await api.post("/leads", editing); setEditing(null); load(); };
  const exportCsv = async () => { if (!clientId) return; const { data } = await api.get(`/leads/client/${clientId}/export.csv`, { responseType: "blob" }); const url = URL.createObjectURL(data); const a = document.createElement("a"); a.href = url; a.download = "leads.csv"; a.click(); };
  return <><PageTitle title="Lead Delivery" subtitle="Log delivered leads, update quality, and export client CSVs." action={<div className="flex gap-2"><Button variant="secondary" disabled={!clientId} onClick={exportCsv}><Download size={16}/> CSV</Button><Button onClick={() => setEditing({ ...blank, clientId: clientId || clients[0]?.id || "" })}><Plus size={16}/> Log Lead</Button></div>} /><div className="mb-4 max-w-sm"><select className={inputClass} value={clientId} onChange={(e) => setClientId(e.target.value)}><option value="">All clients</option>{clients.map((c) => <option key={c.id} value={c.id}>{c.businessName}</option>)}</select></div><DataTable rows={leads} columns={[{ key: "leadName", label: "Lead" }, { key: "businessName", label: "Business" }, { key: "client", label: "Client", render: (r) => r.client?.businessName }, { key: "source", label: "Source", render: (r) => label(r.source) }, { key: "quality", label: "Quality", render: (r) => label(r.quality) }, { key: "status", label: "Status", render: (r) => <select className="rounded border px-2 py-1" value={r.status} onChange={async (e) => { await api.put(`/leads/${r.id}`, { status: e.target.value }); load(); }}>{["NEW", "CONTACTED_BY_CLIENT", "CONVERTED", "NOT_INTERESTED"].map((s) => <option key={s} value={s}>{label(s)}</option>)}</select> }, { key: "deliveredAt", label: "Delivered", render: (r) => dateUk(r.deliveredAt) }]} />{editing && <LeadForm lead={editing} setLead={setEditing} clients={clients} onSave={save} onClose={() => setEditing(null)} />}</>;
}
function LeadForm({ lead, setLead, clients, onSave, onClose }) {
  const set = (key, value) => setLead({ ...lead, [key]: value });
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/50 p-4"><form onSubmit={onSave} className="w-full max-w-3xl rounded-lg bg-white p-6 shadow-xl"><h2 className="mb-4 text-xl font-semibold">Log Lead</h2><div className="grid gap-4 md:grid-cols-2"><Field label="Client"><select required className={inputClass} value={lead.clientId} onChange={(e) => set("clientId", e.target.value)}>{clients.map((c) => <option key={c.id} value={c.id}>{c.businessName}</option>)}</select></Field>{["leadName", "businessName", "email", "phone"].map((k) => <Field key={k} label={label(k)}><input required={k !== "phone"} className={inputClass} value={lead[k]} onChange={(e) => set(k, e.target.value)} /></Field>)}<Field label="Source"><select className={inputClass} value={lead.source} onChange={(e) => set("source", e.target.value)}>{["COLD_EMAIL", "META_AD", "GOOGLE_AD", "REFERRAL"].map((s) => <option key={s} value={s}>{label(s)}</option>)}</select></Field><Field label="Quality"><select className={inputClass} value={lead.quality} onChange={(e) => set("quality", e.target.value)}>{["HOT", "WARM", "COLD"].map((s) => <option key={s} value={s}>{label(s)}</option>)}</select></Field><Field label="Delivered"><input className={inputClass} type="date" value={lead.deliveredAt} onChange={(e) => set("deliveredAt", e.target.value)} /></Field><Field label="Notes"><textarea className={inputClass} value={lead.notes} onChange={(e) => set("notes", e.target.value)} /></Field></div><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button>Save</Button></div></form></div>;
}
